### ISSUE TITLE
Regrading context-specific model reconstruction with generic Human-GEM (Human 1 model)

### ISSUE THREAD

**Issue by sangmi9618** [sysbiolux/rFASTCORMICS#2]
Hi. I've been trying to use rFASTCORMICS for context-specific model reconstruction.
I used Human-GEM (Human 1) model as generic model, Ham's media as medium, and RNA-seq data (RPKM values) of each sample.

Occasionally, `Error: Inconsistent irreversible core reactions.` message appeared for some samples. 
When I check the output model of them, their model contents were empty.

I want to know why this message appears and how to solve the problem.
Can you help me with this situation?

**Comment by mariapirespacheco** [comment]
Hi,
Did you run fastcc on human1 before ?
Human is an inconsistent model. You need first to run Fastcc
And the build a consistent model out of it


here is the pseudocode ( I are on holidays without good internet connexion
so I cannot access github)



A=fastcc(ihuman,1e-4) %find the index of the reactions that are not blocked

model = removeRxns(ihuman, ihuman.rxns(setdiff(1:numel(ihuman.rxns),A)))
% removes the blocked reactions
% removeRxns is a function of the Cobra toolbox which needs to be in the
path


you then  run rFastcormics on model (which is consistent)

Hope this helps

**Comment by sangmi9618** [comment]
Hi.
Thank you for your fast response.
Yes. I did run fastcc on human1 before running rFASTCORMICS.
Following is the code that I ran. Can you check it?&nbsp;
As I said before, the problem is for not all of the samples, just some samples.

initCobraToolbox(false);
addpath(genpath('/data/sangmi/Human-GEM')); % Add the Human 1 directory to MATLAB path 
addpath(genpath('~/rFASTCORMICS/'));
changeCobraSolver('ibm_cplex');
solverOK=changeCobraSolver('ibm_cplex','all');

% Load Human1 model
load("Human-GEM.mat");
%Removing gene version from the model
genes = ihuman.genes;
for i=1:numel(genes)
    x = strsplit(table2array(genes(i,1)),'.');
    genes(i,1) = cellstr(x(1,1));
end
ihuman.genes = genes;

% Set reversible rxns
ihuman.rev= zeros(numel(ihuman.rxns),1);
ihuman.rev(ihuman.lb<0)=1;

A = fastcc_4_rfastcormics(ihuman, 1e-4, 0);
models_keep = zeros(numel(ihuman.rxns), 1);
models_keep(A,1) = 1;
ihuman = removeRxns(ihuman,ihuman.rxns(setdiff(1:numel(ihuman.rxns),find(models_keep(:,1)))));

% setting model reconstruction parameters
already_mapped_tag = 0;
consensus_proportion = 0.9;
epsilon = 1e-4;
load('dico_rFASTCORMICS.mat');

%add atp demand reaction and biomass reaction
optional_settings.func = {'HMR_3964','biomass_human'}; 
% need to define medium for the cells used here
load('ham_medium.mat');
optional_settings.medium = medium;


% RNA-seq data load (.csv file, FPKM values)
fpkm = readtable('./RNASeqdata/pcawg/rnaSeq1_from240_grlee_survivalTest_data_PCAWG_matlabINPUT.csv');
rownames = fpkm(:,1);
rownames = table2array(rownames);
fpkm.Properties.RowNames = table2array(fpkm(:,1));
fpkm = fpkm(:,2:end);
colnames_all_ = fpkm.Properties.VariableNames;
fpkm = table2array(fpkm);
discretized = discretize_FPKM(fpkm, colnames_all_);

% rFASTCORMICS model reconstruction 
for k=1:numel(colnames_all_) % for each sample
    if ~exist('./Models/rFASTCORMICS_pcawg/'+string(colnames_all_{k})+'.mat', 'dir')
        disp(colnames_all_{k});
        % Reconstruct context-specific model
        [model_out, A] = fastcormics_RNAseq(ihuman, discretized(:,k), rownames, dico,'biomass_human', already_mapped_tag, consensus_proportion, 1e-4, optional_settings);

        save('./Models/rFASTCORMICS_pcawg/'+string(colnames_all_{k})+'.mat','model_out');
    end
end 


-----Original Message-----

**Comment by mariapirespacheco** [comment]
Hi did you change the bounds of Human  1? If yes it could be related to it
the flux is so small that is near to epsilon... I would recommend
multiplying the bounds by 1000 before running rFastcormics to go out of the
zone where cplex tends to make an error...
If you did not change the bounds try it anyway and if it still not working
send a minimal example to ***@***.***

Maria

Le ven. 13 août 2021 à 06:13, sangmi9618 ***@***.***> a
écrit :

> Hi.
> Thank you for your fast response.
> Yes. I did run fastcc on human1 before running rFASTCORMICS.
> Following is the code that I ran. Can you check it?&nbsp;
> As I said before, the problem is for not all of the samples, just some
> samples.
>
> initCobraToolbox(false);
> addpath(genpath('/data/sangmi/Human-GEM')); % Add the Human 1 directory to
> MATLAB path&nbsp;
> addpath(genpath('~/rFASTCORMICS/'));
> changeCobraSolver('ibm_cplex');
> solverOK=changeCobraSolver('ibm_cplex','all');
>
> % Load Human1 model
> load("Human-GEM.mat");
> %Removing gene version from the model
> genes = ihuman.genes;
> for i=1:numel(genes)
> &nbsp; &nbsp; x = strsplit(table2array(genes(i,1)),'.');
> &nbsp; &nbsp; genes(i,1) = cellstr(x(1,1));
> end
> ihuman.genes = genes;
>
> % Set reversible rxns
> ihuman.rev= zeros(numel(ihuman.rxns),1);
> ihuman.rev(ihuman.lb&lt;0)=1;
>
> A = fastcc_4_rfastcormics(ihuman, 1e-4, 0);
> models_keep = zeros(numel(ihuman.rxns), 1);
> models_keep(A,1) = 1;
> ihuman =
> removeRxns(ihuman,ihuman.rxns(setdiff(1:numel(ihuman.rxns),find(models_keep(:,1)))));
>
> % setting model reconstruction parameters
> already_mapped_tag = 0;
> consensus_proportion = 0.9;
> epsilon = 1e-4;
> load('dico_rFASTCORMICS.mat');
>
> %add atp demand reaction and biomass reaction
> optional_settings.func = {'HMR_3964','biomass_human'};&nbsp;
> % need to define medium for the cells used here
> load('ham_medium.mat');
> optional_settings.medium = medium;
>
>
> % RNA-seq data load (.csv file, FPKM values)
> fpkm =
> readtable('./RNASeqdata/pcawg/rnaSeq1_from240_grlee_survivalTest_data_PCAWG_matlabINPUT.csv');
> rownames = fpkm(:,1);
> rownames = table2array(rownames);
> fpkm.Properties.RowNames = table2array(fpkm(:,1));
> fpkm = fpkm(:,2:end);
> colnames_all_ = fpkm.Properties.VariableNames;
> fpkm = table2array(fpkm);
> discretized = discretize_FPKM(fpkm, colnames_all_);
>
> % rFASTCORMICS model reconstruction&nbsp;
> for k=1:numel(colnames_all_) % for each sample
> &nbsp; &nbsp; if
> ~exist('./Models/rFASTCORMICS_pcawg/'+string(colnames_all_{k})+'.mat',
> 'dir')
> &nbsp; &nbsp; &nbsp; &nbsp; disp(colnames_all_{k});
> &nbsp; &nbsp; &nbsp; &nbsp; % Reconstruct context-specific model
> &nbsp; &nbsp; &nbsp; &nbsp; [model_out, A] = fastcormics_RNAseq(ihuman,
> discretized(:,k), rownames, dico,'biomass_human', already_mapped_tag,
> consensus_proportion, 1e-4, optional_settings);
>
> &nbsp; &nbsp; &nbsp; &nbsp;
> save('./Models/rFASTCORMICS_pcawg/'+string(colnames_all_{k})+'.mat','model_out');
> &nbsp; &nbsp; end
> end&nbsp;
> &nbsp; &nbsp;&nbsp;
> delete clone*.log %delete some files generated by cplex
>
>
>
> -----Original Message-----
> From: "Maria Pires Pacheco" ***@***.***&gt;
> To: "sysbiolux/rFASTCORMICS" ***@***.***&gt;;
> Cc: "sangmi9618" ***@***.***&gt;; "Author" ***@***.***&gt;;
> Sent: 2021-08-12 (목) 18:42:24 (UTC+09:00)
> Subject: Re: [sysbiolux/rFASTCORMICS] Regrading context-specific model
> reconstruction with generic Human-GEM (Human 1 model) (#2)
>
>
> Hi,
> Did you run fastcc on human1 before ?
> Human is an inconsistent model. You need first to run Fastcc
> And the build a consistent model out of it
>
>
> here is the pseudocode ( I are on holidays without good internet connexion
> so I cannot access github)
>
>
>
> A=fastcc(ihuman,1e-4) %find the index of the reactions that are not blocked
>
> model = removeRxns(ihuman, ihuman.rxns(setdiff(1:numel(ihuman.rxns),A)))
> % removes the blocked reactions
> % removeRxns is a function of the Cobra toolbox which needs to be in the
> path
>
>
> you then run rFastcormics on model (which is consistent)
>
> Hope this helps
>
>
>

**Comment by sangmi9618** [comment]
Hi, I did not change the bounds of Human 1.
I will attached the minimal example code and the required input data I used.&nbsp;
I didn't attached the data (e.g., dico) I used from your rFASTCORMICS repository.
You can run the "rFASTCORMICS_run.m" file.
Can you take a look? I tried a lot to solve this problem, but I couldn't find the cause.

Thanks,
Sang Mi


-----Original Message-----

**Comment by mariapirespacheco** [comment]
Sure I am still in holidays but will try to have a look

**Comment by sangmi9618** [comment]
Have you take a look? I am waiting for your updates.

**Comment by mariapirespacheco** [comment]
Hi i am holidays until monday without good internet and computer so I will
run in monday...

Le mer. 25 août 2021 à 09:54, sangmi9618 ***@***.***> a
écrit :

**Comment by sangmi9618** [comment]
Hi. I'm sorry to rush you, but have you taken a look for this issue?

**Comment by CadavidJoseL** [comment]
I might be out of line jumping in here, but I've tried using FASTCORMICS with the HUMAN-GEM and the error you see is probably due to constraining the algorithm with the minimal media (it never appeared when I removed that constraint). And that might be an interesting thing! It is telling you that some of the core reactions of your sample are not feasible in minimal HAM's medium. If your samples come from an actual tissue, there might be metabolites in that system that are not in the minimal medium.

**Comment by sangmi9618** [comment]
Hi. @CadavidJoseL. Do you mean that I should not specify the `optional_settings.medium`?

**Comment by CadavidJoseL** [comment]
Yes. That might be over-constraining your model. I'd build the models without that constraint to make sure all core reactions are consistent. You can then analyze the model by constraining it with the medium and see what it can actually do.

**Comment by sangmi9618** [comment]
Thanks for your quick reply.
I tried to build the model without medium constraints but it also gave me same error message "Error: Inconsistent irreversible core reactions.:.
Can you share the snippet of your codes?





-----Original Message-----

**Comment by CadavidJoseL** [comment]
What I have so far is something like this (see below). I won't be able to provide more help because I am not working on this too much at the moment.

% Get consistent model
flagged_rxns = fastcc_4_rfastcormics(ihuman, 1e-4,0);
ihuman_cc = removeRxns(ihuman, ihuman.rxns(setdiff(1:numel(ihuman.rxns),flagged_rxns)));

% Get the genes (first column of file) and remove it from the data table.
% These are the 'rownames' needed for FASTCORE
genes_sample = dataTPM.Gene;
dataTPM = dataTPM(:,2:end);
samples = dataTPM.Properties.VariableNames;
% Convert the TPM data to matrix
dataTPM = table2array(dataTPM);

% Modify the gene mapping to have the header names used by FASTCORE. For
% our data we only need the ENSG (used by the template model) and the gene
% symbols (used in the data). Renaming the headers based on the FASTCORE
% example
gene_dico = table(gene_dico.genes, gene_dico.geneSymbols, 'VariableNames', {'ENSG', 'SYMBOL'});

% Discretize the TPM values
dataDiscretized = discretize_FPKM(dataTPM, samples); 
% Optional inputs
biomass_rxn = {'MAR13082'}; % generic biomass reaction in HUMAN-GEM
already_mapped_tag = 0;
epsilon = 1e-4;
consensus_proportion = 0.9;
unpenalizedSystems = {'Transport reactions', 'Exchange/demand reactions'}; % reactions not to be penalized
unpenalized = ihuman_cc.rxns(ismember(vertcat(ihuman_cc.subSystems{:}),unpenalizedSystems));

% Set optional inputs
clear optional_settings
func = {'MAR13082', 'MAR13082'}; % only ATP and biomass required
optional_settings.func = func;

% Loop through all columns to make models
disp('Making models...');
for i = 1:numel(samples)
    fprintf([' ----- Making model for sample ' samples{i} ' ----- \n']);
    % Run fastcore on sample
    [model_out{i}, A_keep{i}] = fastcormics_RNAseq(ihuman_cc, dataDiscretized(:,i), genes_sample, gene_dico, ...
        biomass_rxn, already_mapped_tag, consensus_proportion, epsilon, optional_settings);
    % Add annotation
    model_out{i}.description = strcat('FASTCORE result for sample ', samples{i});
    model_out{i}.id = samples{i};
end

delete clone*.log %delete some files generated by cplex

**Comment by sangmi9618** [comment]
Thank you for sharing your code. It might be helpful to me.
I think it's almost same with my code but I have some questions.
Is "MAR13082" the biomass reaction in Human1 model? In my case, "biomass_human" is the one.
And, when I set the `optional_settings.func` without `optional_settings.medium`, the code cannot detect the optional_settings.
I thought it's because this line `if ~isempty(optional_settings) && isfield(optional_settings, 'medium')` in `fastcormics_RNAseq.m`. Did you change the code of `fastcormics_RNAseq.m`?

**Comment by CadavidJoseL** [comment]
I didn't change anything, and I am using v1.9 of the HUMAN-GEM, in which the naming convention for rxns is different. Unless the authors of FASTCORE have some more insight, this thread is now more of a discussion than an issue. Sorry I can't help more for now!

**Comment by mariapirespacheco** [comment]
The error message often comes when the biomass reaction is not included in the first round but sometimes it comes in the second round. I was on holiday and I was back some a few days but I have been very busy with an urgent task. Can you send me the scripts and model used directly to my email: maria.pacheco@uni.lu
